# Generated by Django 6.0.3 on 2026-04-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la empresa')),
                ('nit', models.CharField(max_length=20, verbose_name='NIT')),
                ('cedula_representante', models.CharField(max_length=20, verbose_name='Cédula del representante legal')),
                ('nombre_representante', models.CharField(max_length=255, verbose_name='Nombre del representante legal')),
                ('enlace_conecta', models.URLField(blank=True, null=True, verbose_name='Enlace de Conecta (si aplica)')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
            ],
        ),
    ]
